variables:
    SERIES_BRANCH: '12.0'
    ODOO_ADMIN_PASS: admin
    CI_JOB_TOKEN_GIT_HOST: 'gitlab.crnd.pro'

    PIP_CACHE_DIR: ".hidden-pip-cache"

# Disable global cache
cache: {}

.pip_cache: &pip_cache_definition
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - "${PIP_CACHE_DIR}"

stages:
    - static-test
    - test
    - translation
    - deploy

build_env:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    script:
        - pwd
        - whoami
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    script:
        - odoo-helper lint flake8 .

pylint:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    script:
        - odoo-helper lint pylint .

bandit:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    <<: *pip_cache_definition
    before_script:
        - odoo-helper pip install bandit
    script:
        - odoo-helper exec bandit -r .

stylelint:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    script:
        - odoo-helper lint style .

check-versions:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    script:
        - odoo-helper ci check-versions-git . origin/$SERIES_BRANCH $CI_COMMIT_SHA
    only:
        - /^12.0-.*$/   # only branches that started with '12.0-'

ensure-changelog:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    script:
        - odoo-helper ci ensure-changelog --format md . origin/$SERIES_BRANCH $CI_COMMIT_SHA
    only:
        - /^12.0-.*$/   # only branches that started with '12.0-'
    allow_failure: true

ensure-icons:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-simple
    stage: static-test
    script:
        - odoo-helper ci ensure-icons .
    only:
        - /^12.0-.*$/   # only branches that started with '12.0-'
    allow_failure: true

tests:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-ci
    stage: test
    <<: *pip_cache_definition
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer test --coverage-report --coverage-fail-under 90 --create-test-db --dir .
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'

migration_tests:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-ci
    stage: test
    <<: *pip_cache_definition
    variables:
        ODOO_DB_NAME: test-db
    before_script:
        - git checkout $SERIES_BRANCH
        - git pull
        - odoo-helper link .
        - odoo-helper --use-unbuffer db create --demo $ODOO_DB_NAME
        - odoo-helper --use-unbuffer addons install -d $ODOO_DB_NAME --dir .
        - git checkout $CI_COMMIT_SHA
        - odoo-helper link .
        - odoo-helper --use-unbuffer addons update-list
        - odoo-helper --use-unbuffer addons update -d $ODOO_DB_NAME --dir .
    script:
        - odoo-helper --use-unbuffer test --coverage-report --coverage-fail-under 90 --dir .
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    only:
        - /^12.0-.*$/   # only branches that started with '12.0-'

translation_rate_ua:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-ci
    stage: translation
    <<: *pip_cache_definition
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer tr rate --lang uk_UA --min-total-rate 70 --dir .
    coverage: '/^TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+|\s+(\d+\.\d+)/'
    allow_failure: true

translation_rate_ru:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:12.0-ci
    stage: translation
    <<: *pip_cache_definition
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer tr rate --lang ru_RU --min-total-rate 70 --dir .
    coverage: '/^TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+|\s+(\d+\.\d+)/'
    allow_failure: true

.deploy_review_definition: &deploy_review_definition
    stage: deploy
    variables:
    before_script:
        - ci-review-app init
    script:
        - ci-review-app start
    tags:
        - traefic
        - review-apps
        - deploy

deploy_review_dev:
    <<: *deploy_review_definition
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: http://$CI_ENVIRONMENT_SLUG-$CI_PROJECT_ID.ci3.crnd.pro
        on_stop: stop_review_dev
    only:
        - /^12.0-.*$/   # only branches that started with '12.0-'
    when: manual

stop_review_dev:
    stage: deploy
    environment:
        name: review/$CI_COMMIT_REF_NAME
        action: stop
    variables:
        GIT_STRATEGY: none
    script:
        - ci-review-app stop
    when: manual
    tags:
        - traefic
        - review-apps
        - deploy
    only:
        - /^12.0-.*$/   # only branches that started with '12.0-'

