image: 10.100.98.41:5000/maao-docker/maao-simple:maao-9.0

variables:
    SERIES_BRANCH: '9.0'
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo

    ODOO_DB_HOST: 10.100.98.41-maao-docker-maao-ci-postgres
    ODOO_DB_USER: odoo
    ODOO_DB_PASSWORD: odoo
    ODOO_ADMIN_PASS: admin

cache:
    paths:
        - "$HOME/.cache/pip"

stages:
    - static-test
    - test
    - translation

build_env:
    stage: static-test
    script:
        - pwd
        - whoami
        - python --version
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    stage: static-test
    script:
        - odoo-helper test flake8 .

pylint:
    stage: static-test
    script:
        - odoo-helper test pylint .

bandit:
    stage: static-test
    before_script:
        - odoo-helper pip install bandit
    script:
        - odoo-helper exec bandit -r .

tests:
    stage: test
    services:
        - 10.100.98.41:5000/maao-docker/maao-ci-postgres

    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer test --coverage --create-test-db -d .
        - odoo-helper exec coverage report --fail-under=90
        - odoo-helper exec coverage html -d html-coverage
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    artifacts:
        paths:
            - html-coverage

migration_tests:
    stage: test
    variables:
        ODOO_DB_NAME: test-db

    services:
        - 10.100.98.41:5000/maao-docker/maao-ci-postgres

    before_script:
        - git checkout $SERIES_BRANCH
        - git pull
        - odoo-helper link .
        - odoo-helper --use-unbuffer db create --demo $ODOO_DB_NAME
        - odoo-helper --use-unbuffer addons install -d $ODOO_DB_NAME $(odoo-helper addons list .)
        - git checkout $CI_COMMIT_SHA
        - rm -rf $(cat .removed_addons.txt)
        - odoo-helper link .
        - odoo-helper --use-unbuffer addons update-list
        - odoo-helper --use-unbuffer addons update -d $ODOO_DB_NAME $(odoo-helper addons list .)
        - odoo-helper --use-unbuffer addons uninstall -d $ODOO_DB_NAME $(cat ./removed_addons.txt)
    script:
        - odoo-helper --use-unbuffer test --coverage -d .
        - odoo-helper exec coverage report --fail-under=90
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    only:
        - /^9.0-.*$/   # only branches that started with '9.0-'

translation_rate_ua:
    stage: translation 
    services:
        - 10.100.98.41:5000/maao-docker/maao-ci-postgres

    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer tr rate --lang uk_UA --min-total-rate 70 $(odoo-helper addons list .)
    coverage: '/^TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+|\s+(\d+\.\d+)/'

translation_rate_ru:
    stage: translation
    services:
        - 10.100.98.41:5000/maao-docker/maao-ci-postgres

    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer tr rate --lang ru_RU $(odoo-helper addons list .)
    coverage: '/^TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+|\s+(\d+\.\d+)/'

